#############################################################################
# Makefile for building: SerialTest
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  SerialTest.pro
# Template: app
# Command: H:/msys64/mingw64/qt5-static/bin/qmake.exe -o Makefile SerialTest.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = H:/msys64/mingw64/qt5-static/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: SerialTest.pro H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/win32-g++/qmake.conf H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/spec_pre.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/qdevice.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/device_config.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/common/angle.conf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/qconfig.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drender.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drenderer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drenderer_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axbase.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axbase_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axcontainer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axserver.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axserver_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_charts.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_core.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_help.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_location.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_network.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_script.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scxml.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_winextras.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_winextras_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_assimpsceneio.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_dsengine.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qgif.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qicns.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qico.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qjp2.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qjpeg.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qminimal.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmng.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsqlite.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsvg.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtga.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtiff.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwbmp.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwebp.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwindows.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_webkit_version.pri \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt_functions.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt_config.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/win32-g++/qmake.conf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/exclusive_builds.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/toolchain.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/default_pre.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/default_pre.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/resolve_config.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/exclusive_builds_post.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/default_post.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/default_post.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/static.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/rtti.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/debug.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/precompile_header.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/debug_and_release.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/warn_on.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/resources.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/moc.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/thread.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qmake_use.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/file_copies.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/windows.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/testcase_targets.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/exceptions.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/yacc.prf \
		H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/lex.prf \
		SerialTest.pro \
		H:/msys64/mingw64/qt5-static/lib/qtmaind.prl \
		H:/msys64/mingw64/qt5-static/lib/Qt5Core.prl
	$(QMAKE) -o Makefile SerialTest.pro
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/spec_pre.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/qdevice.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/device_config.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/common/angle.conf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/qconfig.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dcore.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dextras.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dinput.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquick.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drender.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drenderer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_3drenderer_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axbase.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axbase_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axcontainer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axcontainer_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axserver.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_axserver_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_charts.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_charts_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_core.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_declarative.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designer_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gamepad.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gui.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_help.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_help_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_location.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_location_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_network.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_networkauth.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_nfc.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_purchasing.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qml.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quick.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_script.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_script_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scxml.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialbus.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialport.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sql.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_svg.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_webchannel.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_websockets.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_winextras.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_winextras_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xml.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_assimpsceneio.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_dsengine.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_gltfsceneio.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qdeclarativeview.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qdirect2d.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qgenericbearer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qgif.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qicns.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qico.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qjp2.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qjpeg.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qminimal.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_local.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_native.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_server.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qmng.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qoffscreen.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsqlite.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsvg.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qsvgicon.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtga.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtiff.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qttinycanbus.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwbmp.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwebp.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_qwindows.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_plugin_xinputgamepad.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/modules/qt_webkit_version.pri:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt_functions.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt_config.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/win32-g++/qmake.conf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/exclusive_builds.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/toolchain.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/default_pre.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/default_pre.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/resolve_config.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/exclusive_builds_post.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/default_post.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/default_post.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/static.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/rtti.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/debug.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/precompile_header.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/debug_and_release.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/warn_on.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qt.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/resources.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/moc.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/thread.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/qmake_use.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/file_copies.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/windows.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/testcase_targets.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/win32/exceptions.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/yacc.prf:
H:/msys64/mingw64/qt5-static/share/qt5/mkspecs/features/lex.prf:
SerialTest.pro:
H:/msys64/mingw64/qt5-static/lib/qtmaind.prl:
H:/msys64/mingw64/qt5-static/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SerialTest.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
