######################################################################
# Automatically generated by qmake (3.1) Thu Mar 30 21:23:34 2017
######################################################################

TEMPLATE = app
TARGET = SerialScope
INCLUDEPATH += .
INCLUDEPATH += $$PWD/JuceLibraryCode $$PWD/JuceLibraryCode/modules
INCLUDEPATH += $$PWD/Source/serial/include

CONFIG += link_pkgconfig

PKGCONFIG += freetype2
PKGCONFIG += gtk+-3.0
PKGCONFIG += webkit2gtk-4.0
PKGCONFIG += libcurl

DEFINES += LINUX=1

LIBS += -lXext -lX11 -ldl

# Input
HEADERS += JuceLibraryCode/AppConfig.h \
           JuceLibraryCode/JuceHeader.h \
           Source/MainComponent.h \
           Source/Oscilloscope.h \
           Source/SignalSource.h \
           Source/serialib/serialib.h \
           Source/serial/include/serial/serial.h \
           Source/serial/include/serial/v8stdint.h \
           Source/serial/include/serial/impl/unix.h \
           Source/serial/include/serial/impl/win.h \

           Source/serial/tests/proof_of_concepts
SOURCES += \
           Source/Main.cpp \
           Source/MainComponent.cpp \
           Source/Oscilloscope.cpp \
            Source/serialib/serialib.cpp \
           Source/serial/src/serial.cc \
           Source/serial/src/impl/unix.cc \
           Source/serial/src/impl/win.cc \
              JuceLibraryCode/include_juce_core.cpp JuceLibraryCode/include_juce_cryptography.cpp JuceLibraryCode/include_juce_data_structures.cpp JuceLibraryCode/include_juce_events.cpp JuceLibraryCode/include_juce_graphics.cpp JuceLibraryCode/include_juce_gui_basics.cpp JuceLibraryCode/include_juce_gui_extra.cpp JuceLibraryCode/include_juce_opengl.cpp JuceLibraryCode/include_juce_video.cpp
